"""Deterministic assembly code generator: MateSpec -> AssemblyHelper source.

The assembly-layer analogue of MAC's ``_plan_to_code``: translating the
``AssemblyBrief`` into a build123d ``temp_assembly.py`` costs **zero
tokens**. Only when the closed loop fails does the LLM repair agent see
the generated source.

Reuse from CAD Skills (``positioning.md`` / ``cadpy.assembly``):

* AssemblyHelper + native build123d joints (RigidJoint / RevoluteJoint)
  with fixed-first directionality,
* mate/joint-driven structure instead of raw transforms,
* every anchor is a named datum (bbox face centre / axis point),
* labels survive because parts stay children of the Compound.

Generated script contract
-------------------------
* cwd = assembly job dir; part STEPs referenced by relative path.
* Anchors are derived **at runtime** from each part's bounding box, so
  the script re-measures geometry instead of trusting stale numbers.
* Writes ``assembly_manifest.json`` (per-label placed bbox) which the
  QA engine uses to map exported solids back to part labels.
"""

from __future__ import annotations

from pathlib import Path

from mac_assembly.schemas_assembly import (
    AnchorKind,
    AssemblyBrief,
    MateType,
)

_PRELUDE = '''\
# Generated by mac_assembly.assembly_codegen (deterministic translator).
# Edit only via the assembly repair agent -- regenerate wipes manual edits.
import json
import os
import sys
from pathlib import Path

_REPO_ROOT = Path({repo_root!r})
for _p in (_REPO_ROOT, _REPO_ROOT / "packages" / "cadpy" / "src"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from build123d import Axis, Location, Rotation, Vector, import_step, export_step, export_stl
from cadpy.assembly import AssemblyHelper
from mac_assembly.selector_resolver import resolve_selector_anchor


def _anchor_point(shape, face, axis, offset_mm):
    """Deterministic named-datum -> part-local 3D point (positioning.md)."""
    bb = shape.bounding_box()
    c = bb.center()
    faces = {{
        "top": (c.X, c.Y, bb.max.Z),
        "bottom": (c.X, c.Y, bb.min.Z),
        "right": (bb.max.X, c.Y, c.Z),
        "left": (bb.min.X, c.Y, c.Z),
        "back": (c.X, bb.max.Y, c.Z),
        "front": (c.X, bb.min.Y, c.Z),
    }}
    if face is not None:
        return faces[face]
    d = {{"x": (offset_mm, 0.0, 0.0), "y": (0.0, offset_mm, 0.0),
         "z": (0.0, 0.0, offset_mm)}}[axis]
    return (c.X + d[0], c.Y + d[1], c.Z + d[2])


def _axis_direction(axis):
    return {{"x": (1.0, 0.0, 0.0), "y": (0.0, 1.0, 0.0),
            "z": (0.0, 0.0, 1.0)}}[axis]


# Axial-offset shift math: shared with assembly_qa (single source of truth
# in mac_assembly.geometry_utils so the codegen runtime and QA mirror cannot
# diverge). The subprocess PYTHONPATH includes _PROJECT_ROOT so the import
# resolves at runtime.
from mac_assembly.geometry_utils import shift_pt as _shift_pt


def _resolve_part_step(part_id):
    cand = sorted((Path("parts") / part_id).glob("temp_output_*.step"))
    if not cand:
        raise FileNotFoundError(f"no STEP for part {{part_id!r}} under parts/")
    return cand[-1]


asm = AssemblyHelper({assembly_name!r})
_parts = {{}}
_part_steps = {{}}          # part_id -> STEP path (for SELECTOR resolution)
_audit_selectors = []       # resolved cadpy numeric selectors (audit trail)
'''

_FOOTER = '''\

# ---- build + export -------------------------------------------------------
compound = asm.build()

export_step(compound, {step_out!r})
try:
    export_stl(compound, {stl_out!r}, tolerance=0.05, angular_tolerance=0.3)
except Exception as exc:  # compound STL can fail on odd topologies
    print(f"[assembly] compound STL export failed: {{exc}}")

# Per-label placed bbox manifest -- the QA engine maps exported solids
# back to part labels by nearest bbox centre. Also store each part's world
# Location (translation + Euler XYZ rotation) so QA can transform part-local
# selector points through the FULL placed transform -- not just bbox-centre
# translation -- which is required for kinematic sweeps on chains of revolute
# joints where the fixed part of mate N is itself rotated by mate N-1.
manifest = []
_placed_dir = Path("placed_stl")
_placed_dir.mkdir(exist_ok=True)
for _label, _shape in _parts.items():
    bb = _shape.bounding_box()
    _loc = _shape.location
    manifest.append({{
        "label": _label,
        "bbox_min": [bb.min.X, bb.min.Y, bb.min.Z],
        "bbox_max": [bb.max.X, bb.max.Y, bb.max.Z],
        "location": {{
            "translation": [_loc.position.X, _loc.position.Y, _loc.position.Z],
            "rotation_euler_xyz_deg": [
                _loc.orientation.X, _loc.orientation.Y, _loc.orientation.Z,
            ],
        }},
    }})
    # Per-part placed STL: exact-contact assemblies merge into one shell in
    # the compound STL, so the QA engine cannot split it reliably -- export
    # each part's placed mesh directly instead.
    try:
        export_stl(_shape, str(_placed_dir / f"{{_label}}.stl"),
                   tolerance=0.05, angular_tolerance=0.3)
    except Exception as _exc:
        print(f"[assembly] per-part STL export failed for {{_label}}: {{_exc}}")
with open({manifest_out!r}, "w", encoding="utf-8") as _f:
    json.dump(manifest, _f, indent=2)

with open({mates_out!r}, "w", encoding="utf-8") as _f:
    json.dump([r.__dict__ if hasattr(r, "__dict__") else str(r)
               for r in asm.relations], _f, indent=2, default=str)

# Audit trail: the cadpy numeric selectors each SELECTOR anchor resolved to.
with open({audit_out!r}, "w", encoding="utf-8") as _f:
    json.dump(_audit_selectors, _f, indent=2)

print("[assembly] ASSEMBLY_DONE "
      f"parts={{len(_parts)}} relations={{len(asm.relations)}}")
'''


# Outward normal of each bbox face, as a literal direction tuple.
_FACE_NORMALS = {
    "top": "(0.0, 0.0, 1.0)",
    "bottom": "(0.0, 0.0, -1.0)",
    "right": "(1.0, 0.0, 0.0)",
    "left": "(-1.0, 0.0, 0.0)",
    "back": "(0.0, 1.0, 0.0)",
    "front": "(0.0, -1.0, 0.0)",
}


def _emit_anchor(anchor, part_id: str, tag: str):
    """Emit code to locate an anchor datum.

    Returns ``(setup_lines, point_expr, axis_dir_expr)``:
      * FACE / AXIS_POINT -- pure bbox algebra, no setup lines.
      * SELECTOR -- a runtime cadpy resolution call; the numeric selector it
        matched is recorded for audit (see selector_resolver).
    """
    if getattr(anchor, "kind", None) == AnchorKind.SELECTOR:
        var = f"_sel_{tag}"
        query = dict(
            anchor.selector_query.model_dump(mode="json", exclude_none=True)
        )
        setup = [
            f"{var} = resolve_selector_anchor(_part_steps[{part_id!r}], {query!r})",
            f"if {var} is None:",
            f"    raise RuntimeError(\"SELECTOR anchor matched no face on "
            f"{part_id}: {query!r}\")",
            f"_audit_selectors.append({{'mate_anchor': {tag!r}, 'part': "
            f"{part_id!r}, 'selector': {var}['selector'], 'surface': "
            f"{var}['surface'], 'point': list({var}['point'])}})",
            # N1: the resolver returns PART-LOCAL coords; RigidJoint reads
            # joint_location as world coords at creation time. For an
            # intermediate fixed part that was already moved by an earlier
            # mate, the local point double-counts the displacement --
            # transform through the part's current (accumulated) location.
            # Identity for unmoved parts, so applying to both sides is safe.
            f"{var}_loc = _parts[{part_id!r}].location * Location({var}['point'])",
            # Axis direction in world coords: the resolver returns the
            # cylinder's geometric axis direction in PART-LOCAL coords
            # (sign-normalized to the bbox extent direction). Transform to
            # world by treating the unit axis as a point at the axis
            # direction, transforming it through the part's location, then
            # subtracting the transformed origin -- the result is the
            # rotated unit direction (R*axis, translation cancels out).
            # The previous `_loc - _o` derivation used the resolved POINT
            # (not axis), giving a position vector that was only parallel
            # to the axis when the axis passed through the part origin --
            # for OFFSET axes (e.g. link1's +X post at X=20) the position
            # vector (20,0,20) normalized to (0.71,0,0.71) instead of the
            # correct (0,0,1)). That wrong direction then mis-applied
            # axial_offset_mm (shifted in X and Z instead of just Z).
            f"{var}_o = _parts[{part_id!r}].location * Location((0.0, 0.0, 0.0))",
            f"{var}_ax_loc = _parts[{part_id!r}].location * Location({var}['axis'])",
            f"{var}_ax = ({var}_ax_loc.position.X - {var}_o.position.X, "
            f"{var}_ax_loc.position.Y - {var}_o.position.Y, "
            f"{var}_ax_loc.position.Z - {var}_o.position.Z)",
        ]
        point_expr = (
            f"({var}_loc.position.X, {var}_loc.position.Y, {var}_loc.position.Z)"
        )
        # Axis direction: the transformed resolver axis (always non-zero
        # for a valid cylinder face). Fall back to the raw resolver axis
        # only if the rotation transform produced a degenerate vector.
        return setup, point_expr, (
            f"{var}_ax if abs({var}_ax[0])+abs({var}_ax[1])+abs({var}_ax[2]) > 1e-9 "
            f"else {var}['axis']"
        )

    if getattr(anchor, "kind", None) == AnchorKind.SPHERE:
        # Sphere anchor: explicit sphere center in part-local coords
        # (no SELECTOR resolution needed -- the center is part of the
        # MateSpec). No axis direction (sphere has no preferred axis);
        # the ball mate codegen uses the center as the joint location
        # for both asm.ball_frame() (fixed/socket) and asm.rigid_frame
        # (moving/ball).
        sc = anchor.sphere_center_mm or [0.0, 0.0, 0.0]
        if len(sc) != 3:
            raise ValueError(
                f"sphere_center_mm must have 3 elements [x, y, z], got "
                f"{len(sc)}: {sc!r}"
            )
        point = f"({float(sc[0])!r}, {float(sc[1])!r}, {float(sc[2])!r})"
        return [], point, None

    point = (
        f"_anchor_point(_parts[{part_id!r}], {anchor.face!r}, "
        f"{anchor.axis!r}, {anchor.offset_mm!r})"
    )
    if anchor.kind == AnchorKind.FACE:
        dir_expr = _FACE_NORMALS[anchor.face]
    else:
        dir_expr = f"_axis_direction({(anchor.axis or 'z')!r})"
    return [], point, dir_expr


def _toposort_mates(mates: list, part_ids: set[str]) -> list:
    """Order mates so every fixed part is settled before it anchors others.

    build123d ``connect_to`` is a one-shot placement (positioning.md:
    not a persistent constraint), so a mate whose fixed part is later
    moved by its own mate would leave already-placed children behind
    (B1). Kahn-style: roots (parts that never move) start settled; a
    mate is emitted once its fixed part is settled. Cycle leftovers are
    appended in original order (validation flags them upstream).
    """
    moved = {m.moving_part_id for m in mates}
    settled = set(part_ids) - moved
    order: list = []
    remaining = list(mates)
    while remaining:
        ready = [m for m in remaining if m.fixed_part_id in settled]
        if not ready:
            break  # cycle: remaining mates are never ready; callers flag this
        for m in ready:
            order.append(m)
            settled.add(m.moving_part_id)
        remaining = [m for m in remaining if m not in order]
    return order


def _unsortable_mates(mates: list, part_ids: set[str]) -> list:
    """Mates left over after topological ordering (i.e. on a cycle)."""
    ordered = _toposort_mates(mates, part_ids)
    return [m for m in mates if m not in ordered]


def _axis_ranges_from_spec(part) -> dict[str, dict]:
    """Read per-axis ranges from ``part.key_dimensions['axis_ranges']``.

    Preferred over the prose scraper (``_extract_axis_ranges``) because
    the LLM's prose phrasing varies across runs -- the structured field
    is the authoritative source. Falls back to prose per-part when
    ``axis_ranges`` is absent (old caches, or the LLM skipped the field).

    Accepted formats (per axis, pick one):

    * Simple: ``{"z": [0, 8]}`` -- list of [min, max].
    * With protrusion: ``{"z": {"overall": [0, 8], "protrusion": [0, 8]}}``
      where ``protrusion`` is the sub-feature range (a post / ear / arm
      / shaft / boss). Protrusion is optional; without it the postprocess
      falls back to the overall midpoint for the fixed anchor local coord.

    Returns ``{axis: {"overall_min", "overall_max", "post_min"?, "post_max"?}}``
    -- same dict shape as ``_extract_axis_ranges`` so the postprocess
    logic is identical for both readers. ``post_*`` field names are
    legacy (the prose parser coined them for Z-axis posts); they cover
    any-axis protrusions in both readers. Empty dict if ``axis_ranges``
    absent or malformed.
    """
    raw = (part.key_dimensions or {}).get("axis_ranges")
    if not isinstance(raw, dict):
        return {}
    out: dict[str, dict] = {}
    for axis, spec in raw.items():
        if not isinstance(spec, dict) and not isinstance(spec, list):
            continue
        ax = str(axis).lower()
        if ax not in ("x", "y", "z"):
            continue
        ax_out: dict[str, float] = {}
        overall = spec.get("overall") if isinstance(spec, dict) else spec
        if isinstance(overall, list) and len(overall) == 2:
            try:
                ax_out["overall_min"] = float(overall[0])
                ax_out["overall_max"] = float(overall[1])
            except (TypeError, ValueError):
                continue
        elif isinstance(spec, dict) and "min" in spec and "max" in spec:
            try:
                ax_out["overall_min"] = float(spec["min"])
                ax_out["overall_max"] = float(spec["max"])
            except (TypeError, ValueError):
                continue
        else:
            continue
        if isinstance(spec, dict):
            protr = spec.get("protrusion")
            if isinstance(protr, list) and len(protr) == 2:
                try:
                    ax_out["post_min"] = float(protr[0])
                    ax_out["post_max"] = float(protr[1])
                except (TypeError, ValueError):
                    pass
            elif "protrusion_min" in spec and "protrusion_max" in spec:
                try:
                    ax_out["post_min"] = float(spec["protrusion_min"])
                    ax_out["post_max"] = float(spec["protrusion_max"])
                except (TypeError, ValueError):
                    pass
        out[ax] = ax_out
    return out


def _extract_axis_ranges(description: str, axis: str) -> dict:
    """Extract `<axis>` ranges from a part's prose description.

    The Decomposer's Iron Rule 6 requires every part description to state
    its local coordinate ranges explicitly, but the LLM phrases them
    differently across runs ("Z = 0..8 mm", "Z from 0 to 8", "Z=0 to
    Z=6", "Z=0..6", "Z: 0..8"). This parser handles the common variants
    and generalizes to any principal axis (x/y/z).

    ``axis`` is "x", "y", or "z" (case-insensitive); the regex matches
    the corresponding uppercase letter in the description.

    Returns a dict with axis-agnostic keys (so callers use the same
    field access for any axis):
      - overall_min, overall_max (first parseable <axis> range; the
        part's primary extent along that axis)
      - post_min, post_max (a protrusion's <axis> range, if a feature
        keyword -- "post", "ear", "arm", "shaft", or "boss" -- appears
        within 120 chars before the match, OR by matching "<kw> bottom
        <AX>=X" + "<kw> top <AX>=Y" patterns). The "post" concept is
        Z-specific terminology (vertical cylindrical protrusion); for
        X/Y, the equivalent feature keywords (ear / arm / shaft / boss)
        are also recognized so horizontal protrusions are detected.
    """
    import re

    ax = axis.lower()
    AX = ax.upper()
    num = r"(-?\d+(?:\.\d+)?)"
    # Multiple phrasings of "<AX> from X to Y" the LLM uses. All matches
    # across all patterns are collected and sorted by position; the
    # FIRST is the overall range, subsequent matches with a feature
    # keyword in context are protrusion ranges.
    range_patterns = [
        rf"{AX}\s*=\s*{num}\s*\.\.\s*{num}\s*mm",  # Z = 0..8 mm
        rf"{AX}\s*=\s*{num}\s*\.\.\s*{num}(?!\d)",  # Z = 0..8 (no trailing mm/digit)
        rf"{AX}\s+from\s+{num}\s+to\s+{num}",      # Z from 0 to 8
        rf"{AX}\s*=\s*{num}\s+to\s+{AX}\s*=\s*{num}",  # Z=0 to Z=6
        rf"{AX}\s*:\s*{num}\s*\.\.\s*{num}",       # Z: 0..8
        # Explicit bottom/top pair WITH "and" between (tight; does not
        # match across long distances where a "post top" might appear).
        # The "bottom"/"top" terms are Z-specific, so this only fires
        # for Z-axis descriptions.
        rf"bottom\s+(?:face\s+)?at\s+{AX}\s*=\s*{num}\s+and\s+top\s+(?:face\s+)?at\s+{AX}\s*=\s*{num}",
    ]
    range_pats = [re.compile(p, re.IGNORECASE | re.DOTALL) for p in range_patterns]

    matches = []
    for pat in range_pats:
        for m in pat.finditer(description):
            matches.append(m)
    if not matches:
        return {}

    # Deduplicate by (start, end) position; sort by position.
    seen = set()
    unique = []
    for m in matches:
        if (m.start(), m.end()) not in seen:
            seen.add((m.start(), m.end()))
            unique.append(m)
    unique.sort(key=lambda m: m.start())

    overall = unique[0]
    out = {
        "overall_min": float(overall.group(1)),
        "overall_max": float(overall.group(2)),
    }

    # Look for a protrusion (post/ear/arm/shaft/boss) range: any later
    # <axis> range match preceded by one of the feature keywords within
    # 120 chars. This distinguishes the protrusion's range from the
    # part's overall range. The keyword set covers Z ("post") and X/Y
    # ("ear"/"arm"/"shaft"/"boss") protrusions uniformly.
    feature_keywords = ("post", "ear", "arm", "shaft", "boss")
    for m in unique[1:]:
        ctx_start = max(0, m.start() - 120)
        ctx = description[ctx_start:m.start()].lower()
        if any(kw in ctx for kw in feature_keywords):
            out["post_min"] = float(m.group(1))
            out["post_max"] = float(m.group(2))
            break

    # Fallback for protrusions described by separate "<kw> bottom <AX>=X"
    # and "<kw> top <AX>=Y" patterns (instead of a single range). The
    # "bottom"/"top" terms are Z-specific, so this only fires for Z-axis
    # descriptions.
    if "post_min" not in out:
        feat_pat = "|".join(feature_keywords)
        post_bottom_pat = re.compile(
            rf"(?:{feat_pat})\s+bottom[^.]*?{AX}\s*=\s*{num}",
            re.IGNORECASE | re.DOTALL,
        )
        post_top_pat = re.compile(
            rf"(?:{feat_pat})\s+top[^.]*?{AX}\s*=\s*{num}",
            re.IGNORECASE | re.DOTALL,
        )
        bm = post_bottom_pat.search(description)
        tm = post_top_pat.search(description)
        if bm and tm:
            out["post_min"] = float(bm.group(1))
            out["post_max"] = float(tm.group(1))

    return out


def _get_anchor_axis(anchor) -> str | None:
    """Determine the principal axis (x/y/z) of an anchor, or None.

    For SELECTOR cylinder: returns `selector_query.axis` (the cylinder's
    axis direction).
    For AXIS_POINT: returns `anchor.axis` if the offset is small (a
    through-bore midpoint, within 1mm of the part's bbox centre along
    that axis). Non-zero offsets reflect a specific design intent and
    return None (the postprocess leaves the LLM's axial_offset alone).
    For FACE: returns the face normal axis (top/bottom=z, left/right=x,
    front/back=y).

    This generalizes the previous Z-only `_is_z_anchor` predicate to
    any of the three principal axes.
    """
    if anchor.kind == AnchorKind.SELECTOR and anchor.selector_query:
        if anchor.selector_query.surface == "cylinder":
            return str(anchor.selector_query.axis).lower()
        return None
    if anchor.kind == AnchorKind.AXIS_POINT:
        if abs(anchor.offset_mm or 0.0) <= 1.0:
            return str(anchor.axis).lower() if anchor.axis else None
        return None
    if anchor.kind == AnchorKind.FACE:
        face_axis_map = {
            "top": "z", "bottom": "z",
            "left": "x", "right": "x",
            "front": "y", "back": "y",
        }
        return face_axis_map.get(str(anchor.face).lower()) if anchor.face else None
    return None


def postprocess_axial_offsets(plan, brief) -> "MatingPlan":  # type: ignore[no-untyped-def]
    """Deterministic ``axial_offset_mm`` override for revolute mates
    along ANY principal axis (x/y/z).

    The Mating Architect LLM consistently writes wrong ``axial_offset_mm``
    values in the JSON field despite correct reasoning in ``notes``
    (classic thinking-vs-output inconsistency: notes say "axial_offset =
    11 - 14 = -3" but the JSON field ends up as -11.0). For the common
    pivot-post + link-bar and link-bar + link-bar revolute patterns --
    the canonical finger-palm and finger-finger joints -- the offset
    can be computed deterministically from the brief's prose ranges
    (mandatory per the Decomposer's Iron Rule 6), bypassing the LLM's
    arithmetic.

    Generalized from Z-only to any principal axis: the override fires
    whenever both anchors reference the SAME principal axis (SELECTOR
    cylinder axis=<x|y|z>, AXIS_POINT axis=<x|y|z> with small offset,
    or FACE whose normal is along that axis). The chain offset tracking
    is per-axis, so mixed-axis chains (e.g. shoulder yaw + elbow pitch)
    are handled correctly when each joint's static pose is a pure
    translation (no rotation); rotated static poses break the chain
    tracking and the override skips (LLM's value kept).

    Pattern matched (all must hold for an override):
      - mate_type == REVOLUTE
      - both anchors reference the same principal axis (x, y, or z)
      - fixed part's description has a parseable range along that axis
      - moving part's description has a parseable range along that axis

    Formula ("seat on +axis face" semantics -- moving's -axis face
    lands on fixed's +axis face):

        fixed_anchor_local = (post_min + post_max) / 2  if protrusion
                                                           else overall midpoint
        fixed_top_local    = overall_max  (+axis face)
        moving_anchor_local = (overall_min + overall_max) / 2  (through-bore)

        fixed_anchor_world = fixed_anchor_local + world_offset[axis][fixed_pid]
        fixed_top_world    = fixed_top_local     + world_offset[axis][fixed_pid]
        axial_offset_mm    = fixed_top_world + moving_anchor_local
                                              - fixed_anchor_world
        world_offset[axis][moving_pid] = fixed_top_world  (chain tracking)

    For the unmoved root, world_offset[axis][pid] = 0. For moved parts,
    it is the fixed_top_world of the mate that placed them. Mates are
    processed in toposort order so the fixed part's chain is settled
    first. Per-axis tracking means a part on a Z-chain gets
    world_offset[z] set, while a part on an X-chain gets world_offset[x]
    set; mixed-axis chains with translation-only static poses work
    (each axis tracked independently).

    Returns the plan with overridden mates (original mate order
    preserved). Mates that don't match the pattern keep the LLM's value.
    """
    pids = {p.part_id for p in brief.parts}
    part_by_id = {p.part_id: p for p in brief.parts}
    ordered = _toposort_mates(plan.mates, pids)

    # Per-axis chain offset: world_offset[axis][pid] = world coord of
    # pid's local origin along `axis`. Independent per axis so mixed-axis
    # chains with translation-only static poses work.
    world_offset: dict[str, dict[str, float]] = {
        ax: {pid: 0.0 for pid in pids} for ax in ("x", "y", "z")
    }
    overrides: dict[str, float] = {}

    # Structured axis_ranges (preferred over prose scrape): precompute
    # per-part once so each mate lookup is O(1). Empty dict per part
    # when key_dimensions.axis_ranges is absent -- the prose scrape
    # (called per mate below) picks up old-cache parts.
    structured_ranges: dict[str, dict] = {
        pid: _axis_ranges_from_spec(part) for pid, part in part_by_id.items()
    }

    for mate in ordered:
        if mate.mate_type != MateType.REVOLUTE:
            continue
        fa, ma = mate.fixed_anchor, mate.moving_anchor

        # Both anchors must reference the same principal axis (x/y/z).
        # SELECTOR cylinder returns selector_query.axis; AXIS_POINT
        # returns anchor.axis (with small offset); FACE returns the
        # face-normal axis. Mismatched or non-principal axes -> skip
        # (LLM's value kept).
        axis = _get_anchor_axis(fa)
        if axis is None or axis != _get_anchor_axis(ma):
            continue

        fixed_part = part_by_id.get(mate.fixed_part_id)
        moving_part = part_by_id.get(mate.moving_part_id)
        if not fixed_part or not moving_part:
            continue

        # Structured axis_ranges first (authoritative); prose scrape as
        # fallback for parts whose key_dimensions.axis_ranges is absent
        # (old cache) or doesn't include this axis. The fallback's
        # brittleness is contained to legacy data; new briefs always
        # hit the structured path.
        fixed_r = structured_ranges.get(fixed_part.part_id, {}).get(axis) \
            or _extract_axis_ranges(fixed_part.description, axis)
        moving_r = structured_ranges.get(moving_part.part_id, {}).get(axis) \
            or _extract_axis_ranges(moving_part.description, axis)
        if not fixed_r or not moving_r:
            continue
        if "overall_min" not in fixed_r or "overall_max" not in fixed_r:
            continue
        if "overall_min" not in moving_r or "overall_max" not in moving_r:
            continue

        # Coplanar guard: if the two parts' overall ranges along `axis`
        # overlap by more than 50% of the smaller extent, this is a
        # same-axis-layer joint (e.g. clevis planar chain), NOT a
        # stacking joint. The "seat on +axis face" override below would
        # incorrectly stack the moving part on the +axis side of the
        # fixed part. Skip and keep the LLM's axial_offset_mm (typically
        # 0 for coplanar clevis joints).
        # Robustness: a thick palm (T=25mm) + thin finger (T=8mm) gives
        # overlap_ratio = 8/8 = 1.0 (smaller_extent base), still judged
        # coplanar. Stacked parts (Z=0..8 + Z=8..14) give overlap_ratio
        # = 0 -> override fires.
        f_min = float(fixed_r["overall_min"])
        f_max = float(fixed_r["overall_max"])
        m_min = float(moving_r["overall_min"])
        m_max = float(moving_r["overall_max"])
        overlap = max(0.0, min(f_max, m_max) - max(f_min, m_min))
        smaller_extent = min(f_max - f_min, m_max - m_min)
        overlap_ratio = (
            overlap / smaller_extent if smaller_extent > 0 else 0.0
        )
        if overlap_ratio > 0.5:
            continue

        # Fixed anchor local coord: protrusion midpoint if there's a
        # post/ear/arm, else the overall midpoint (a bar's bore midpoint).
        if "post_min" in fixed_r and "post_max" in fixed_r:
            fixed_anchor_local = (fixed_r["post_min"] + fixed_r["post_max"]) / 2.0
            # The surface the moving seats on is the body's +axis face
            # (the protrusion emerges from the body; the moving sits on
            # the body, not on the protrusion's tip).
            fixed_top_local = fixed_r["overall_max"]
        else:
            fixed_anchor_local = (
                fixed_r["overall_min"] + fixed_r["overall_max"]
            ) / 2.0
            fixed_top_local = fixed_r["overall_max"]

        # Moving anchor local coord: through-bore midpoint = overall midpoint.
        moving_anchor_local = (
            moving_r["overall_min"] + moving_r["overall_max"]
        ) / 2.0

        fixed_off = world_offset[axis].get(mate.fixed_part_id, 0.0)
        fixed_anchor_world = fixed_anchor_local + fixed_off
        fixed_top_world = fixed_top_local + fixed_off

        axial_offset = (
            fixed_top_world + moving_anchor_local - fixed_anchor_world
        )
        overrides[mate.mate_id] = axial_offset

        # Moving's -axis face lands on fixed's +axis face -> chain to children.
        world_offset[axis][mate.moving_part_id] = fixed_top_world

    if not overrides:
        return plan

    new_mates = []
    for mate in plan.mates:
        if mate.mate_id in overrides:
            new_mates.append(mate.model_copy(
                update={"axial_offset_mm": overrides[mate.mate_id]}
            ))
        else:
            new_mates.append(mate)
    return plan.model_copy(update={"mates": new_mates})


def _mate_block(i: int, mate) -> str:
    """Deterministic MateSpec -> AssemblyHelper calls (zero tokens)."""
    fid, mid = mate.fixed_part_id, mate.moving_part_id
    fa, ma = mate.fixed_anchor, mate.moving_anchor
    f_setup, fx, f_dir = _emit_anchor(fa, fid, f"fixed_{mate.mate_id}")
    m_setup, mx, m_dir = _emit_anchor(ma, mid, f"moving_{mate.mate_id}")
    lines = [f"# mate {mate.mate_id} ({mate.mate_type.value}): {fid} <- {mid}"]
    lines += f_setup + m_setup

    if mate.mate_type in (MateType.RIGID, MateType.FACE_TO_FACE):
        # RIGID + axial_offset_mm: shift the fixed frame along the anchor
        # direction (face normal / axis_point axis / SELECTOR axis). Use
        # this to position a moving part at a SPECIFIC offset from the
        # fixed anchor -- e.g. a second ear 90mm to the right of the first
        # ear, when both ears' hole midpoints are the SELECTOR anchors
        # (rigid aligns the two midpoints exactly; axial_offset_mm slides
        # the moving part along the cylinder axis to its actual target X).
        # For FACE_TO_FACE, the face_to_face mate's own offset_mm handles
        # the +Z gap; axial_offset_mm is unused there.
        if mate.mate_type == MateType.RIGID and mate.axial_offset_mm:
            fx_eff = f"_shift_pt({fx}, {f_dir}, {mate.axial_offset_mm!r})"
        else:
            fx_eff = fx
        lines += [
            f"_f{i} = asm.rigid_frame(_parts[{fid!r}], {('fixed_' + mate.mate_id)!r}, Location({fx_eff}))",
            f"_m{i} = asm.rigid_frame(_parts[{mid!r}], {('moving_' + mate.mate_id)!r}, Location({mx}))",
        ]
        if mate.mate_type == MateType.FACE_TO_FACE:
            lines.append(
                f"asm.face_to_face(_f{i}, _m{i}, offset={mate.offset_mm!r}, "
                f"label={mate.mate_id!r})"
            )
        else:
            lines.append(
                f"asm.connect(_f{i}, _m{i}, relation='rigid', label={mate.mate_id!r})"
            )
    elif mate.mate_type in (MateType.COAXIAL, MateType.REVOLUTE):
        # build123d pairing: RevoluteJoint.connect_to expects a RigidJoint
        # on the moving side -- the fixed side carries the rotation axis.
        # RevoluteJoint's default angular_range is (0, 360): normalize
        # negative static poses into that range (B3). Axis direction comes
        # from the anchor (face normal / axis_point axis / SELECTOR normal).
        # axial_offset_mm (revolute/coaxial only): shift the fixed frame's
        # point along the rotation axis so the moving part seats at the
        # desired axial position. Both anchors resolve to cylinder midpoints
        # by default; without this offset, the moving part floats at the
        # fixed cylinder's midpoint rather than seating on a surface.
        if mate.axial_offset_mm:
            fx_eff = f"_shift_pt({fx}, {f_dir}, {mate.axial_offset_mm!r})"
        else:
            fx_eff = fx
        # Precompensation: build123d's RevoluteJoint.connect_to implicitly
        # reframes the moving part so its local +Z aligns with the fixed
        # axis direction. For axis=+Z this is a no-op (identity rotation),
        # but for axis=+X or +Y the moving part picks up an unwanted
        # ~90° rotation that breaks the joint geometry -- e.g. a finger
        # segment whose long axis is Y ends up along X after the reframe,
        # making the assembled finger lie sideways. Pre-rotate the moving
        # RigidJoint's joint_location by the inverse reframe so build123d's
        # reframe cancels out, leaving the moving part with identity
        # orientation relative to its source geometry. Empirically derived
        # via build123d testing (Rotation(R,P,Y) where RPY produces identity
        # moving orientation after connect_to):
        #   axis=+X → Rotation(0, 90, 180)
        #   axis=+Y → Rotation(-90, 0, -90)
        #   axis=+Z → Rotation(0, 0, 0) (no precomp needed)
        fixed_axis = _get_anchor_axis(mate.fixed_anchor) or "z"
        _PRECOMP_RPY = {
            "x": (0.0, 90.0, 180.0),
            "y": (-90.0, 0.0, -90.0),
            "z": (0.0, 0.0, 0.0),
        }
        precomp_rpy = _PRECOMP_RPY.get(fixed_axis, (0.0, 0.0, 0.0))
        if precomp_rpy == (0.0, 0.0, 0.0):
            moving_loc_expr = f"Location({mx})"
        else:
            moving_loc_expr = (
                f"Location({mx}) * Rotation({precomp_rpy[0]!r}, "
                f"{precomp_rpy[1]!r}, {precomp_rpy[2]!r})"
            )
        lines += [
            f"_fa{i} = Axis({fx_eff}, {f_dir})",
            f"_f{i} = asm.revolute_frame(_parts[{fid!r}], {('fixed_' + mate.mate_id)!r}, _fa{i})",
            f"_m{i} = asm.rigid_frame(_parts[{mid!r}], {('moving_' + mate.mate_id)!r}, {moving_loc_expr})",
        ]
        if mate.mate_type == MateType.COAXIAL:
            lines.append(
                f"asm.connect(_f{i}, _m{i}, relation='coaxial', label={mate.mate_id!r})"
            )
        else:
            lines.append(
                f"asm.revolute(_f{i}, _m{i}, angle={mate.angle_deg % 360!r}, "
                f"label={mate.mate_id!r})"
            )
    elif mate.mate_type in (MateType.LINEAR, MateType.CYLINDRICAL):
        # LinearJoint / CylindricalJoint.connect_to expect a RigidJoint on
        # the moving side; the fixed side carries the slide axis. The slide
        # DIRECTION comes from mate.slide_axis; the anchor points locate the
        # datum. Default linear_range is (0, inf) -- widen it so negative
        # poses are legal. angle is the static rotation about the slide axis
        # (normalized into [0,360) like revolute; R1 -- was silently dropped).
        sax = mate.slide_axis or "x"
        frame_method = (
            "linear_frame" if mate.mate_type == MateType.LINEAR
            else "cylindrical_frame"
        )
        lines += [
            f"_fa{i} = Axis({fx}, _axis_direction({sax!r}))",
            f"_f{i} = asm.{frame_method}(_parts[{fid!r}], {('fixed_' + mate.mate_id)!r}, "
            f"_fa{i}, linear_range=(-100000.0, 100000.0))",
            f"_m{i} = asm.rigid_frame(_parts[{mid!r}], {('moving_' + mate.mate_id)!r}, Location({mx}))",
            f"asm.connect(_f{i}, _m{i}, relation={mate.mate_type.value!r}, "
            f"position={mate.position_mm!r}, angle={mate.angle_deg % 360!r}, "
            f"label={mate.mate_id!r})",
        ]
    elif mate.mate_type == MateType.BALL:
        # Ball mate: BallJoint on the fixed (socket) side at the sphere
        # center; RigidJoint on the moving (ball) side at the ball's sphere
        # center. asm.ball() connects them with a 3-tuple `angles`
        # (RotationLike = X/Y/Z gimbal). 2-DOF constraint per spec: roll
        # (the third element) is always 0 -- pitch + yaw only. Both
        # anchors must be kind=sphere (validated in _validate_mating_plan);
        # fx and mx are the sphere-center 3-tuples from _emit_anchor.
        lines += [
            f"_f{i} = asm.ball_frame(_parts[{fid!r}], "
            f"{('fixed_' + mate.mate_id)!r}, Location({fx}))",
            f"_m{i} = asm.rigid_frame(_parts[{mid!r}], "
            f"{('moving_' + mate.mate_id)!r}, Location({mx}))",
            f"asm.ball(_f{i}, _m{i}, "
            f"angles=({mate.ball_pitch_deg!r}, {mate.ball_yaw_deg!r}, 0.0), "
            f"label={mate.mate_id!r})",
        ]
    else:  # pragma: no cover - enum is closed
        lines.append(f"# UNSUPPORTED mate type {mate.mate_type} -> skipped")
    return "\n".join(lines)


def generate_assembly_script(
    brief: AssemblyBrief,
    mates: list,
    repo_root: Path,
) -> str:
    """Render the full ``temp_assembly.py`` source text.

    ``brief`` supplies the parts; ``mates`` (the MatingPlan's MateSpec
    list) supplies placement. The split mirrors MAC's Spec Planner /
    Architect division of labour.
    """
    head = _PRELUDE.format(
        repo_root=str(repo_root),
        assembly_name=brief.assembly_name,
    )

    body_lines = []
    for spec in brief.parts:
        body_lines += [
            f"_step_path = _resolve_part_step({spec.part_id!r})",
            f"_parts[{spec.part_id!r}] = asm.add(import_step(_step_path), {spec.part_id!r})",
            f"_part_steps[{spec.part_id!r}] = str(_step_path)",
        ]

    # B1 fix: execute in topological order (fixed parts settle first).
    # Cycle leftovers (invalid plans) are emitted best-effort after; the
    # validation layer flags them upstream before codegen is reached.
    pids = {p.part_id for p in brief.parts}
    ordered = _toposort_mates(mates, pids) + _unsortable_mates(mates, pids)
    for i, mate in enumerate(ordered):
        body_lines.append(_mate_block(i, mate))

    foot = _FOOTER.format(
        step_out="assembly_output.step",
        stl_out="assembly_output.stl",
        manifest_out="assembly_manifest.json",
        mates_out="assembly_mates.json",
        audit_out="assembly_selector_audit.json",
    )
    return head + "\n".join(body_lines) + "\n" + foot


def write_assembly_script(
    brief: AssemblyBrief,
    mates: list,
    assembly_dir: Path,
    repo_root: Path,
    iteration: int = 0,
) -> Path:
    """Write ``temp_assembly_{iteration}.py`` into the assembly job dir."""
    src = generate_assembly_script(brief, mates, repo_root)
    path = assembly_dir / f"temp_assembly_{iteration}.py"
    path.write_text(src, encoding="utf-8")
    return path


def run_assembly_script(
    script_path: Path,
    assembly_dir: Path,
    *,
    timeout: int,
    python_bin: str = "",
) -> tuple[bool, str]:
    """Execute the generated assembly script (cwd-isolated subprocess)."""
    import os
    import shutil
    import subprocess
    import sys

    # Delete stale outputs from a previous iteration BEFORE running the script.
    # Without this, a script that crashes after import_step but before
    # export_step leaves the prior assembly_output.step on disk; the assembler
    # node still sets assembly_step_path to that path; the QA node's
    # Path(...).is_file() check passes; run_assembly_qa runs detectors on the
    # STALE geometry; if the stale geometry happened to PASS, the router
    # terminates the loop and the user receives the previous iteration's
    # assembly believing it is the new one. Deleting pre-run guarantees a
    # crashed script leaves no STEP, so QA correctly synthesizes FATAL.
    for stale_name in (
        "assembly_output.step",
        "assembly_output.stl",
        "assembly_manifest.json",
        "assembly_mates.json",
        "assembly_selector_audit.json",
    ):
        try:
            (assembly_dir / stale_name).unlink()
        except FileNotFoundError:
            pass
        except OSError:  # pragma: no cover - best-effort cleanup
            pass
    placed_dir = assembly_dir / "placed_stl"
    if placed_dir.is_dir():
        shutil.rmtree(placed_dir, ignore_errors=True)

    python = python_bin or sys.executable
    env = dict(os.environ)
    env["ITERATION"] = "0"
    try:
        proc = subprocess.run(  # noqa: S603
            [python, str(script_path)],
            cwd=str(assembly_dir),
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            timeout=timeout,
        )
        out = proc.stdout or ""
        (assembly_dir / "assembly_log.txt").write_text(out, encoding="utf-8")
        step = assembly_dir / "assembly_output.step"
        ok = proc.returncode == 0 and step.is_file() and step.stat().st_size > 0
        tail = " | ".join(
            ln for ln in out.splitlines() if ln.strip()
        )[-600:]
        return ok, tail
    except subprocess.TimeoutExpired:
        return False, f"assembly script timed out after {timeout}s"
    except Exception as exc:  # noqa: BLE001
        return False, f"assembly script crashed: {exc}"
