"""Deterministic assembly code generator: MateSpec -> AssemblyHelper source.

The assembly-layer analogue of MAC's ``_plan_to_code``: translating the
``AssemblyBrief`` into a build123d ``temp_assembly.py`` costs **zero
tokens**. Only when the closed loop fails does the LLM repair agent see
the generated source.

Reuse from CAD Skills (``positioning.md`` / ``cadpy.assembly``):

* AssemblyHelper + native build123d joints (RigidJoint / RevoluteJoint)
  with fixed-first directionality,
* mate/joint-driven structure instead of raw transforms,
* every anchor is a named datum (bbox face centre / axis point),
* labels survive because parts stay children of the Compound.

Generated script contract
-------------------------
* cwd = assembly job dir; part STEPs referenced by relative path.
* Anchors are derived **at runtime** from each part's bounding box, so
  the script re-measures geometry instead of trusting stale numbers.
* Writes ``assembly_manifest.json`` (per-label placed bbox) which the
  QA engine uses to map exported solids back to part labels.
"""

from __future__ import annotations

import math
from pathlib import Path

from mac_assembly.geometry_utils import FACE_AXIS, FACE_NORMALS
from mac_assembly.schemas_assembly import (
    AnchorKind,
    AssemblyBrief,
    MateType,
)

_PRELUDE = '''\
# Generated by mac_assembly.assembly_codegen (deterministic translator).
# Edit only via the assembly repair agent -- regenerate wipes manual edits.
import json
import os
import sys
from pathlib import Path

_REPO_ROOT = Path({repo_root!r})
for _p in (_REPO_ROOT, _REPO_ROOT / "packages" / "cadpy" / "src"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from build123d import Axis, Location, Rotation, Vector, import_step, export_step, export_stl
from cadpy.assembly import AssemblyHelper
from mac_assembly.selector_resolver import resolve_selector_anchor


def _anchor_point(shape, face, axis, offset_mm):
    """Deterministic named datum transformed from part-local to world.

    ``shape.bounding_box()`` is world-axis aligned after a parent mate has
    rotated the part, so reading a named face/axis point directly from it
    selects a different physical datum. Recover the original local bbox,
    evaluate the datum there, then apply the full current Location.
    """
    loc = shape.location
    bb = shape.moved(loc.inverse()).bounding_box()
    c = bb.center()
    faces = {{
        "top": (c.X, c.Y, bb.max.Z),
        "bottom": (c.X, c.Y, bb.min.Z),
        "right": (bb.max.X, c.Y, c.Z),
        "left": (bb.min.X, c.Y, c.Z),
        "back": (c.X, bb.max.Y, c.Z),
        "front": (c.X, bb.min.Y, c.Z),
    }}
    if face is not None:
        p = faces[face]
        w = loc * Location(p)
        return (w.position.X, w.position.Y, w.position.Z)
    d = {{"x": (offset_mm, 0.0, 0.0), "y": (0.0, offset_mm, 0.0),
         "z": (0.0, 0.0, offset_mm)}}[axis]
    p = (c.X + d[0], c.Y + d[1], c.Z + d[2])
    w = loc * Location(p)
    return (w.position.X, w.position.Y, w.position.Z)


def _local_point(shape, point):
    """Transform an explicit part-local point through the current pose."""
    w = shape.location * Location(point)
    return (w.position.X, w.position.Y, w.position.Z)


def _axis_direction(axis):
    return {{"x": (1.0, 0.0, 0.0), "y": (0.0, 1.0, 0.0),
            "z": (0.0, 0.0, 1.0)}}[axis]


# Axial-offset shift math: shared with assembly_qa (single source of truth
# in mac_assembly.geometry_utils so the codegen runtime and QA mirror cannot
# diverge). The subprocess PYTHONPATH includes _PROJECT_ROOT so the import
# resolves at runtime.
from mac_assembly.geometry_utils import shift_pt as _shift_pt
from mac_assembly.geometry_utils import snap_axis as _snap_axis


def _world_axis_dir(part, axis_name):
    # A mate's slide/joint axis is principal (x/y/z) in the FIXED part's
    # LOCAL frame. When the fixed part was itself placed by an earlier mate
    # (chained joints), its local axis is rotated in world -- transform it
    # through the part's current location (rotation only: the transformed
    # endpoint minus the transformed origin cancels the translation), then
    # snap away the ~1e-16 float noise so OCP's gp_Ax3 branch stays
    # deterministic (see geometry_utils.snap_axis). Identity for unmoved
    # parts, so pure-translation assemblies are byte-identical to before.
    _d = {{"x": (1.0, 0.0, 0.0), "y": (0.0, 1.0, 0.0),
          "z": (0.0, 0.0, 1.0)}}[axis_name]
    _o = part.location * Location((0.0, 0.0, 0.0))
    _e = part.location * Location(_d)
    _ax = (_e.position.X - _o.position.X,
           _e.position.Y - _o.position.Y,
           _e.position.Z - _o.position.Z)
    if abs(_ax[0]) + abs(_ax[1]) + abs(_ax[2]) < 1e-9:
        return _d
    return _snap_axis(_ax)


def _shift_xyz(point, part, delta_local):
    """Shift a world point by a vector expressed in ``part`` local axes."""
    _x = _world_axis_dir(part, "x")
    _y = _world_axis_dir(part, "y")
    _z = _world_axis_dir(part, "z")
    return (
        point[0] + delta_local[0] * _x[0] + delta_local[1] * _y[0] + delta_local[2] * _z[0],
        point[1] + delta_local[0] * _x[1] + delta_local[1] * _y[1] + delta_local[2] * _z[1],
        point[2] + delta_local[0] * _x[2] + delta_local[1] * _y[2] + delta_local[2] * _z[2],
    )


def _resolve_part_step(part_id):
    # 1. AUTHORITATIVE path: the PartResult's step_path recorded by the
    #    part_builder this iteration (passed in via _PART_STEP_OVERRIDES).
    #    Guards against a stale STEP file left in the part directory (e.g.
    #    a failed regeneration keeps the previous temp_output_features.step)
    #    being picked up by the mtime glob below and masquerading as this
    #    round's geometry. When an override IS recorded but the file is
    #    gone, we FAIL LOUDLY (FileNotFoundError) instead of falling back
    #    to the glob: the fallback could resurrect exactly the stale
    #    geometry the override exists to prevent, silently assembling
    #    last round's part as this round's result.
    # 2. Legacy compatibility mode (NO override recorded for this part,
    #    e.g. a script generated before part_step_overrides existed):
    #    newest temp_output_*.step by mtime (delegates to
    #    mac_assembly.file_utils.newest_file, single source of truth, R3):
    #    mtime primary, trailing iteration number as tiebreak -- NEVER
    #    alphabetical ("temp_output_10" < "temp_output_2" lexicographically).
    #    The subprocess PYTHONPATH includes the project root, so the import
    #    resolves at runtime (same as geometry_utils).
    _ovr = _PART_STEP_OVERRIDES.get(part_id)
    if _ovr is not None:
        _p = Path(_ovr)
        if _p.is_file():
            return _p
        raise FileNotFoundError(
            f"authoritative STEP for part {{part_id!r}} recorded at {{_ovr}} "
            f"is missing -- refusing the stale-glob fallback (it could pick "
            f"up an older temp_output_*.step and masquerade as this round's "
            f"geometry); rebuild the part or clear the override"
        )
    from mac_assembly.file_utils import newest_file as _nf
    p = _nf(Path("parts") / part_id, "temp_output_*.step")
    if p is None:
        raise FileNotFoundError(f"no STEP for part {{part_id!r}} under parts/")
    return p


asm = AssemblyHelper({assembly_name!r})
_parts = {{}}
_part_steps = {{}}          # part_id -> STEP path (for SELECTOR resolution)
_audit_selectors = []       # resolved cadpy numeric selectors (audit trail)
# part_id -> authoritative STEP path (relative to this cwd) from THIS
# iteration's PartResults -- see _resolve_part_step. Empty dict when the
# caller has no part results (legacy behaviour: mtime glob only).
_PART_STEP_OVERRIDES = {part_step_overrides!r}
'''

_FOOTER = '''\

# ---- build + export -------------------------------------------------------
compound = asm.build()

export_step(compound, {step_out!r})
try:
    export_stl(compound, {stl_out!r}, tolerance=0.05, angular_tolerance=0.3)
except Exception as exc:  # compound STL can fail on odd topologies
    print(f"[assembly] compound STL export failed: {{exc}}")

# Per-label placed bbox manifest -- the QA engine maps exported solids
# back to part labels by nearest bbox centre. Also store each part's world
# Location (translation + Euler XYZ rotation) so QA can transform part-local
# selector points through the FULL placed transform -- not just bbox-centre
# translation -- which is required for kinematic sweeps on chains of revolute
# joints where the fixed part of mate N is itself rotated by mate N-1.
manifest = []
_placed_dir = Path("placed_stl")
_placed_dir.mkdir(exist_ok=True)
for _label, _shape in _parts.items():
    bb = _shape.bounding_box()
    _loc = _shape.location
    manifest.append({{
        "label": _label,
        "bbox_min": [bb.min.X, bb.min.Y, bb.min.Z],
        "bbox_max": [bb.max.X, bb.max.Y, bb.max.Z],
        "location": {{
            "translation": [_loc.position.X, _loc.position.Y, _loc.position.Z],
            "rotation_euler_xyz_deg": [
                _loc.orientation.X, _loc.orientation.Y, _loc.orientation.Z,
            ],
        }},
    }})
    # Per-part placed STL: exact-contact assemblies merge into one shell in
    # the compound STL, so the QA engine cannot split it reliably -- export
    # each part's placed mesh directly instead.
    try:
        export_stl(_shape, str(_placed_dir / f"{{_label}}.stl"),
                   tolerance=0.05, angular_tolerance=0.3)
    except Exception as _exc:
        print(f"[assembly] per-part STL export failed for {{_label}}: {{_exc}}")
with open({manifest_out!r}, "w", encoding="utf-8") as _f:
    json.dump(manifest, _f, indent=2)

# Merge MateSpec joint limits into the relation records by mate label
# (build123d relations don't carry them). Consumed by urdf_export (D3).
_mate_limits = {mate_limits!r}
_recs = [r.__dict__ if hasattr(r, "__dict__") else str(r)
         for r in asm.relations]
for _rec in _recs:
    if isinstance(_rec, dict):
        _rec.update(_mate_limits.get(_rec.get("label"), {{}}))
with open({mates_out!r}, "w", encoding="utf-8") as _f:
    json.dump(_recs, _f, indent=2, default=str)

# Audit trail: the cadpy numeric selectors each SELECTOR anchor resolved to.
with open({audit_out!r}, "w", encoding="utf-8") as _f:
    json.dump(_audit_selectors, _f, indent=2)

print("[assembly] ASSEMBLY_DONE "
      f"parts={{len(_parts)}} relations={{len(asm.relations)}}")
'''


# Outward normals of bbox faces come from geometry_utils.FACE_NORMALS
# (single source of truth, R1); str(tuple) reproduces the literal form the
# generated source expects.


def _emit_anchor(anchor, part_id: str, tag: str):
    """Emit code to locate an anchor datum.

    Returns ``(setup_lines, point_expr, axis_dir_expr)``:
      * FACE / AXIS_POINT -- pure bbox algebra, no setup lines.
      * SELECTOR -- a runtime cadpy resolution call; the numeric selector it
        matched is recorded for audit (see selector_resolver).
    """
    if getattr(anchor, "kind", None) == AnchorKind.SELECTOR:
        var = f"_sel_{tag}"
        query = dict(
            anchor.selector_query.model_dump(mode="json", exclude_none=True)
        )
        setup = [
            f"{var} = resolve_selector_anchor(_part_steps[{part_id!r}], {query!r})",
            f"if {var} is None:",
            f"    raise RuntimeError(\"SELECTOR anchor matched no face on "
            f"{part_id}: {query!r}\")",
            f"_audit_selectors.append({{'mate_anchor': {tag!r}, 'part': "
            f"{part_id!r}, 'selector': {var}['selector'], 'surface': "
            f"{var}['surface'], 'point': list({var}['point'])}})",
            # N1: the resolver returns PART-LOCAL coords; RigidJoint reads
            # joint_location as world coords at creation time. For an
            # intermediate fixed part that was already moved by an earlier
            # mate, the local point double-counts the displacement --
            # transform through the part's current (accumulated) location.
            # Identity for unmoved parts, so applying to both sides is safe.
            f"{var}_loc = _parts[{part_id!r}].location * Location({var}['point'])",
            # Axis direction in world coords: the resolver returns the
            # cylinder's geometric axis direction in PART-LOCAL coords
            # (sign-normalized to the bbox extent direction). Transform to
            # world by treating the unit axis as a point at the axis
            # direction, transforming it through the part's location, then
            # subtracting the transformed origin -- the result is the
            # rotated unit direction (R*axis, translation cancels out).
            # The previous `_loc - _o` derivation used the resolved POINT
            # (not axis), giving a position vector that was only parallel
            # to the axis when the axis passed through the part origin --
            # for OFFSET axes (e.g. link1's +X post at X=20) the position
            # vector (20,0,20) normalized to (0.71,0,0.71) instead of the
            # correct (0,0,1)). That wrong direction then mis-applied
            # axial_offset_mm (shifted in X and Z instead of just Z).
            f"{var}_o = _parts[{part_id!r}].location * Location((0.0, 0.0, 0.0))",
            f"{var}_ax_loc = _parts[{part_id!r}].location * Location({var}['axis'])",
            f"{var}_ax = ({var}_ax_loc.position.X - {var}_o.position.X, "
            f"{var}_ax_loc.position.Y - {var}_o.position.Y, "
            f"{var}_ax_loc.position.Z - {var}_o.position.Z)",
        ]
        point_expr = (
            f"({var}_loc.position.X, {var}_loc.position.Y, {var}_loc.position.Z)"
        )
        # Axis direction: the transformed resolver axis (always non-zero
        # for a valid cylinder face). Fall back to the raw resolver axis
        # only if the rotation transform produced a degenerate vector.
        # _snap_axis: the transform through the fixed part's placed Location
        # injects ~1e-16 noise into axis-aligned bore axes, which can flip
        # OCP gp_Ax3's default-x_dir branch (see geometry_utils.snap_axis)
        # and roll the mated part 90 deg about the joint axis.
        return setup, point_expr, (
            f"_snap_axis({var}_ax) if abs({var}_ax[0])+abs({var}_ax[1])+abs({var}_ax[2]) > 1e-9 "
            f"else _snap_axis({var}['axis'])"
        )

    if getattr(anchor, "kind", None) == AnchorKind.SPHERE:
        # Sphere anchor: explicit sphere center in part-local coords
        # (no SELECTOR resolution needed -- the center is part of the
        # MateSpec). No axis direction (sphere has no preferred axis);
        # the ball mate codegen uses the center as the joint location
        # for both asm.ball_frame() (fixed/socket) and asm.rigid_frame
        # (moving/ball).
        sc = anchor.sphere_center_mm or [0.0, 0.0, 0.0]
        # The schema is the strict layer: Anchor._check_kind_fields already
        # enforces len==3 at parse time (B12), and QA bare-indexes sc[0..2]
        # under that guarantee. This raise is a defense-in-depth assert for
        # objects that bypassed validation (e.g. model_construct).
        if len(sc) != 3:
            raise ValueError(
                f"sphere_center_mm must have 3 elements [x, y, z], got "
                f"{len(sc)}: {sc!r}"
            )
        point = f"({float(sc[0])!r}, {float(sc[1])!r}, {float(sc[2])!r})"
        return [], point, None

    point = (
        f"_local_point(_parts[{part_id!r}], {tuple(anchor.point_mm)!r})"
        if anchor.kind == AnchorKind.AXIS_POINT and anchor.point_mm is not None
        else f"_anchor_point(_parts[{part_id!r}], {anchor.face!r}, "
             f"{anchor.axis!r}, {anchor.offset_mm!r})"
    )
    if anchor.kind == AnchorKind.FACE:
        # str() of the tuple reproduces the "(0.0, 0.0, 1.0)" literal form
        # the generated source expects.
        dir_expr = str(FACE_NORMALS[anchor.face])
    else:
        dir_expr = f"_axis_direction({(anchor.axis or 'z')!r})"
    return [], point, dir_expr


def _axis_rot_matrix(axis: str, deg: float) -> list[list[float]]:
    """3x3 rotation matrix about a principal axis (right-hand rule)."""
    r = math.radians(deg)
    c, s = math.cos(r), math.sin(r)
    if axis == "x":
        return [[1.0, 0.0, 0.0], [0.0, c, -s], [0.0, s, c]]
    if axis == "y":
        return [[c, 0.0, s], [0.0, 1.0, 0.0], [-s, 0.0, c]]
    return [[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]]


def _mat3_mul(a: list[list[float]], b: list[list[float]]) -> list[list[float]]:
    return [[sum(a[i][k] * b[k][j] for k in range(3)) for j in range(3)]
            for i in range(3)]


def _to_intrinsic_xyz(r: list[list[float]]) -> tuple[float, float, float]:
    """Decompose R into build123d's intrinsic-XYZ Euler triple (degrees).

    build123d ``Rotation(X, Y, Z)`` (Intrinsic.XYZ) composes as
    ``R = Rx(X) @ Ry(Y) @ Rz(Z)`` -- verified numerically against
    build123d. Extraction: Y = atan2(R02, hypot(R00, R01)),
    X = atan2(-R12, R22), Z = atan2(-R01, R00); at gimbal lock
    (|R02| = 1) set X = 0 and recover Z = atan2(R10, R11), which is
    correct for both Y = +90 and Y = -90.
    """
    y = math.atan2(r[0][2], math.hypot(r[0][0], r[0][1]))
    if abs(abs(r[0][2]) - 1.0) < 1e-9:
        x, z = 0.0, math.atan2(r[1][0], r[1][1])
    else:
        x = math.atan2(-r[1][2], r[2][2])
        z = math.atan2(-r[0][1], r[0][0])
    return (math.degrees(x), math.degrees(y), math.degrees(z))


def _ball_angles_euler(axis1: str, angle1: float, axis2: str,
                       angle2: float) -> tuple[float, float, float]:
    """Static pose of a ball mate as an intrinsic-XYZ Euler triple.

    The joint's two DOFs are rotations about ``axis1`` (first, in the
    joint frame) then ``axis2`` (in the post-first-rotation frame) --
    matching the URDF decomposition's serial chain, whose total world
    rotation is ``R_axis1(a1) @ R_axis2(a2)``. BallJoint only accepts an
    Euler triple or a single Rotation, and ``Rotation * Rotation``
    returns a plain Location (rejected by ``relative_to``), so the
    composed rotation is converted to the equivalent Euler triple here
    at generation time (zero-token deterministic math). Slots stay
    signed (the natural +-180 decomposition): the emitted ball_frame
    widens angular_range to +-360 per slot, because ``relative_to``
    re-derives the orientation and range-checks THAT, so a normalized
    [0,360) input like 330 would still fail as -30.
    """
    r = _mat3_mul(_axis_rot_matrix(axis1, angle1),
                  _axis_rot_matrix(axis2, angle2))
    return tuple(round(v, 9) for v in _to_intrinsic_xyz(r))


def _toposort_mates(mates: list, part_ids: set[str]) -> list:
    """Order mates so every fixed part is settled before it anchors others.

    build123d ``connect_to`` is a one-shot placement (positioning.md:
    not a persistent constraint), so a mate whose fixed part is later
    moved by its own mate would leave already-placed children behind
    (B1). Kahn-style: roots (parts that never move) start settled; a
    mate is emitted once its fixed part is settled. Cycle leftovers are
    appended in original order (validation flags them upstream).
    """
    moved = {m.moving_part_id for m in mates}
    settled = set(part_ids) - moved
    order: list = []
    remaining = list(mates)
    while remaining:
        ready = [m for m in remaining if m.fixed_part_id in settled]
        if not ready:
            break  # cycle: remaining mates are never ready; callers flag this
        for m in ready:
            order.append(m)
            settled.add(m.moving_part_id)
        ordered_ids = {m.mate_id for m in order}
        remaining = [m for m in remaining if m.mate_id not in ordered_ids]
    return order


def _axis_ranges_from_spec(part) -> dict[str, dict]:
    """Read per-axis ranges from ``part.key_dimensions['axis_ranges']``.

    Preferred over the prose scraper (``_extract_axis_ranges``) because
    the LLM's prose phrasing varies across runs -- the structured field
    is the authoritative source. Falls back to prose per-part when
    ``axis_ranges`` is absent (old caches, or the LLM skipped the field).

    Accepted formats (per axis, pick one):

    * Simple: ``{"z": [0, 8]}`` -- list of [min, max].
    * With protrusion: ``{"z": {"overall": [0, 8], "protrusion": [0, 8]}}``
      where ``protrusion`` is the sub-feature range (a post / ear / arm
      / shaft / boss). Protrusion is optional; without it the postprocess
      falls back to the overall midpoint for the fixed anchor local coord.

    Returns ``{axis: {"overall_min", "overall_max", "post_min"?, "post_max"?}}``
    -- same dict shape as ``_extract_axis_ranges`` so the postprocess
    logic is identical for both readers. ``post_*`` field names are
    legacy (the prose parser coined them for Z-axis posts); they cover
    any-axis protrusions in both readers. Empty dict if ``axis_ranges``
    absent or malformed.
    """
    raw = (part.key_dimensions or {}).get("axis_ranges")
    if not isinstance(raw, dict):
        return {}
    out: dict[str, dict] = {}
    for axis, spec in raw.items():
        if not isinstance(spec, dict) and not isinstance(spec, list):
            continue
        ax = str(axis).lower()
        if ax not in ("x", "y", "z"):
            continue
        ax_out: dict[str, float] = {}
        overall = spec.get("overall") if isinstance(spec, dict) else spec
        if isinstance(overall, list) and len(overall) == 2:
            try:
                ax_out["overall_min"] = float(overall[0])
                ax_out["overall_max"] = float(overall[1])
            except (TypeError, ValueError):
                continue
        elif isinstance(spec, dict) and "min" in spec and "max" in spec:
            try:
                ax_out["overall_min"] = float(spec["min"])
                ax_out["overall_max"] = float(spec["max"])
            except (TypeError, ValueError):
                continue
        else:
            continue
        if isinstance(spec, dict):
            protr = spec.get("protrusion")
            if isinstance(protr, list) and len(protr) == 2:
                try:
                    ax_out["post_min"] = float(protr[0])
                    ax_out["post_max"] = float(protr[1])
                except (TypeError, ValueError):
                    pass
            elif "protrusion_min" in spec and "protrusion_max" in spec:
                try:
                    ax_out["post_min"] = float(spec["protrusion_min"])
                    ax_out["post_max"] = float(spec["protrusion_max"])
                except (TypeError, ValueError):
                    pass
        out[ax] = ax_out
    return out


def _extract_axis_ranges(description: str, axis: str) -> dict:
    """Extract `<axis>` ranges from a part's prose description.

    The Decomposer's Iron Rule 6 requires every part description to state
    its local coordinate ranges explicitly, but the LLM phrases them
    differently across runs ("Z = 0..8 mm", "Z from 0 to 8", "Z=0 to
    Z=6", "Z=0..6", "Z: 0..8"). This parser handles the common variants
    and generalizes to any principal axis (x/y/z).

    ``axis`` is "x", "y", or "z" (case-insensitive); the regex matches
    the corresponding uppercase letter in the description.

    Returns a dict with axis-agnostic keys (so callers use the same
    field access for any axis):
      - overall_min, overall_max (first parseable <axis> range; the
        part's primary extent along that axis)
      - post_min, post_max (a protrusion's <axis> range, if a feature
        keyword -- "post", "ear", "arm", "shaft", or "boss" -- appears
        within 120 chars before the match, OR by matching "<kw> bottom
        <AX>=X" + "<kw> top <AX>=Y" patterns). The "post" concept is
        Z-specific terminology (vertical cylindrical protrusion); for
        X/Y, the equivalent feature keywords (ear / arm / shaft / boss)
        are also recognized so horizontal protrusions are detected.
    """
    import re

    ax = axis.lower()
    AX = ax.upper()
    num = r"(-?\d+(?:\.\d+)?)"
    # Multiple phrasings of "<AX> from X to Y" the LLM uses. All matches
    # across all patterns are collected and sorted by position; the
    # FIRST is the overall range, subsequent matches with a feature
    # keyword in context are protrusion ranges.
    range_patterns = [
        rf"{AX}\s*=\s*{num}\s*\.\.\s*{num}\s*mm",  # Z = 0..8 mm
        rf"{AX}\s*=\s*{num}\s*\.\.\s*{num}(?!\d)",  # Z = 0..8 (no trailing mm/digit)
        rf"{AX}\s+from\s+{num}\s+to\s+{num}",      # Z from 0 to 8
        rf"{AX}\s*=\s*{num}\s+to\s+{AX}\s*=\s*{num}",  # Z=0 to Z=6
        rf"{AX}\s*:\s*{num}\s*\.\.\s*{num}",       # Z: 0..8
        # Explicit bottom/top pair WITH "and" between (tight; does not
        # match across long distances where a "post top" might appear).
        # The "bottom"/"top" terms are Z-specific, so this only fires
        # for Z-axis descriptions.
        rf"bottom\s+(?:face\s+)?at\s+{AX}\s*=\s*{num}\s+and\s+top\s+(?:face\s+)?at\s+{AX}\s*=\s*{num}",
    ]
    range_pats = [re.compile(p, re.IGNORECASE | re.DOTALL) for p in range_patterns]

    matches = []
    for pat in range_pats:
        for m in pat.finditer(description):
            matches.append(m)
    if not matches:
        return {}

    # Deduplicate by (start, end) position; sort by position.
    seen = set()
    unique = []
    for m in matches:
        if (m.start(), m.end()) not in seen:
            seen.add((m.start(), m.end()))
            unique.append(m)
    unique.sort(key=lambda m: m.start())

    overall = unique[0]
    out = {
        "overall_min": float(overall.group(1)),
        "overall_max": float(overall.group(2)),
    }

    # Look for a protrusion (post/ear/arm/shaft/boss) range: any later
    # <axis> range match preceded by one of the feature keywords within
    # 120 chars. This distinguishes the protrusion's range from the
    # part's overall range. The keyword set covers Z ("post") and X/Y
    # ("ear"/"arm"/"shaft"/"boss") protrusions uniformly.
    feature_keywords = ("post", "ear", "arm", "shaft", "boss")
    for m in unique[1:]:
        ctx_start = max(0, m.start() - 120)
        ctx = description[ctx_start:m.start()].lower()
        if any(kw in ctx for kw in feature_keywords):
            out["post_min"] = float(m.group(1))
            out["post_max"] = float(m.group(2))
            break

    # Fallback for protrusions described by separate "<kw> bottom <AX>=X"
    # and "<kw> top <AX>=Y" patterns (instead of a single range). The
    # "bottom"/"top" terms are Z-specific, so this only fires for Z-axis
    # descriptions.
    if "post_min" not in out:
        feat_pat = "|".join(feature_keywords)
        post_bottom_pat = re.compile(
            rf"(?:{feat_pat})\s+bottom[^.]*?{AX}\s*=\s*{num}",
            re.IGNORECASE | re.DOTALL,
        )
        post_top_pat = re.compile(
            rf"(?:{feat_pat})\s+top[^.]*?{AX}\s*=\s*{num}",
            re.IGNORECASE | re.DOTALL,
        )
        bm = post_bottom_pat.search(description)
        tm = post_top_pat.search(description)
        if bm and tm:
            out["post_min"] = float(bm.group(1))
            out["post_max"] = float(tm.group(1))

    return out


def _get_anchor_axis(anchor) -> str | None:
    """Determine the principal axis (x/y/z) of an anchor, or None.

    For SELECTOR cylinder: returns `selector_query.axis` (the cylinder's
    axis direction).
    For AXIS_POINT: returns `anchor.axis` if the offset is small (a
    through-bore midpoint, within 1mm of the part's bbox centre along
    that axis). Non-zero offsets reflect a specific design intent and
    return None (the postprocess leaves the LLM's axial_offset alone).
    For FACE: returns the face normal axis (top/bottom=z, left/right=x,
    front/back=y).

    This generalizes the previous Z-only `_is_z_anchor` predicate to
    any of the three principal axes.
    """
    if anchor.kind == AnchorKind.SELECTOR and anchor.selector_query:
        if anchor.selector_query.surface == "cylinder":
            return str(anchor.selector_query.axis).lower()
        return None
    if anchor.kind == AnchorKind.AXIS_POINT:
        if abs(anchor.offset_mm or 0.0) <= 1.0:
            return str(anchor.axis).lower() if anchor.axis else None
        return None
    if anchor.kind == AnchorKind.FACE:
        return FACE_AXIS.get(str(anchor.face).lower()) if anchor.face else None
    return None


def _anchor_axis_letter(anchor) -> str | None:
    """The anchor's principal axis letter (x/y/z), offset-agnostic.

    Unlike ``_get_anchor_axis`` -- whose ``None`` for |offset_mm| > 1
    axis_points tells ``postprocess_axial_offsets`` to leave the LLM's
    ``axial_offset_mm`` alone -- this is the plain axis the anchor names:
    ``axis_point.axis`` at ANY offset (the mating prompt's canonical
    revolute example uses offsets 12.5/-30.0, and its guidance recommends
    joint-end datums at half the part extent), selector_query.axis for
    cylinder AND plane queries (a plane's normal is a valid hinge axis --
    the turntable pattern), or the FACE normal axis. Consumers: plan
    validation's principal-axis gate and the revolute precompensation
    matrix (which previously fell back to 'z' for large-offset axis_point
    anchors, mis-rotating x/y-axis hinges).
    """
    kind = getattr(anchor, "kind", None)
    if kind == AnchorKind.SELECTOR and anchor.selector_query is not None:
        return str(anchor.selector_query.axis).lower() or None
    if kind == AnchorKind.AXIS_POINT:
        return str(anchor.axis).lower() if anchor.axis else None
    if kind == AnchorKind.FACE:
        return FACE_AXIS.get(str(anchor.face).lower()) if anchor.face else None
    return None


def postprocess_axial_offsets(plan, brief) -> "MatingPlan":  # type: ignore[no-untyped-def]
    """Deterministic ``axial_offset_mm`` override for revolute mates
    along ANY principal axis (x/y/z).

    The Mating Architect LLM consistently writes wrong ``axial_offset_mm``
    values in the JSON field despite correct reasoning in ``notes``
    (classic thinking-vs-output inconsistency: notes say "axial_offset =
    11 - 14 = -3" but the JSON field ends up as -11.0). For the common
    pivot-post + link-bar and link-bar + link-bar revolute patterns --
    the canonical finger-palm and finger-finger joints -- the offset
    can be computed deterministically from the brief's prose ranges
    (mandatory per the Decomposer's Iron Rule 6), bypassing the LLM's
    arithmetic.

    Generalized from Z-only to any principal axis: the override fires
    whenever both anchors reference the SAME principal axis (SELECTOR
    cylinder axis=<x|y|z>, AXIS_POINT axis=<x|y|z> with small offset,
    or FACE whose normal is along that axis).

    Pattern matched (all must hold for an override):
      - mate_type == REVOLUTE
      - both anchors reference the same principal axis (x, y, or z)
      - fixed part's description has a parseable range along that axis
      - moving part's description has a parseable range along that axis

    Formula ("seat on +axis face" semantics -- moving's -axis face
    lands on fixed's +axis face):

        fixed_anchor_local  = (post_min + post_max) / 2  if protrusion
                                                        else overall midpoint
        fixed_top_local     = overall_max  (+axis face)
        moving_anchor_local = (overall_min + overall_max) / 2  (through-bore)

        axial_offset_mm = fixed_top_local + moving_anchor_local
                                           - fixed_anchor_local

    The formula is purely LOCAL: axial_offset_mm is applied to the fixed
    part's frame, so any world translation of the fixed part (its own
    placement in a chain) would add to both fixed_top and fixed_anchor
    and cancels out -- an earlier "chain tracking" mechanism propagated
    such offsets per axis and algebraically never changed a single
    override value, so it was removed (R2).

    Returns the plan with overridden mates (original mate order
    preserved). Mates that don't match the pattern keep the LLM's value.
    """
    # Normalize a common rigid-placement failure before the revolute
    # heuristics below: the anchors already define the datum coincidence,
    # but the LLM repeats the same absolute coordinate in axial_offset or in
    # the normal component of translation_mm.  That double-applies stacking
    # height and creates obviously floating decks/sensors.
    normalized_mates = []
    for mate in plan.mates:
        if mate.mate_type != MateType.RIGID:
            normalized_mates.append(mate)
            continue
        fa, ma = mate.fixed_anchor, mate.moving_anchor
        # Offset-agnostic axis identity is required here: large axis_point
        # offsets are exactly the top/bottom datum pattern being normalized,
        # and planar SELECTOR anchors also have a meaningful normal axis.
        axis = _anchor_axis_letter(fa)
        same_axis = axis is not None and axis == _anchor_axis_letter(ma)
        updates = {}
        if same_axis and (
            (fa.kind == AnchorKind.AXIS_POINT and ma.kind == AnchorKind.AXIS_POINT)
            or (
                (fa.kind == AnchorKind.FACE or (
                    fa.kind == AnchorKind.SELECTOR
                    and fa.selector_query is not None
                    and fa.selector_query.surface == "plane"
                ))
                and (ma.kind == AnchorKind.FACE or (
                    ma.kind == AnchorKind.SELECTOR
                    and ma.selector_query is not None
                    and ma.selector_query.surface == "plane"
                ))
            )
        ):
            updates["axial_offset_mm"] = 0.0
            translation = list(mate.translation_mm)
            translation[{"x": 0, "y": 1, "z": 2}[axis]] = 0.0
            updates["translation_mm"] = translation
        normalized_mates.append(mate.model_copy(update=updates) if updates else mate)
    plan = plan.model_copy(update={"mates": normalized_mates})

    pids = {p.part_id for p in brief.parts}
    part_by_id = {p.part_id: p for p in brief.parts}
    ordered = _toposort_mates(plan.mates, pids)

    overrides: dict[str, float] = {}

    # Structured axis_ranges (preferred over prose scrape): precompute
    # per-part once so each mate lookup is O(1). Empty dict per part
    # when key_dimensions.axis_ranges is absent -- the prose scrape
    # (called per mate below) picks up old-cache parts.
    structured_ranges: dict[str, dict] = {
        pid: _axis_ranges_from_spec(part) for pid, part in part_by_id.items()
    }

    for mate in ordered:
        if mate.mate_type != MateType.REVOLUTE:
            continue
        fa, ma = mate.fixed_anchor, mate.moving_anchor

        # Both anchors must reference the same principal axis (x/y/z).
        # SELECTOR cylinder returns selector_query.axis; AXIS_POINT
        # returns anchor.axis (with small offset); FACE returns the
        # face-normal axis. Mismatched or non-principal axes -> skip
        # (LLM's value kept).
        axis = _get_anchor_axis(fa)
        if axis is None or axis != _get_anchor_axis(ma):
            continue

        fixed_part = part_by_id.get(mate.fixed_part_id)
        moving_part = part_by_id.get(mate.moving_part_id)
        if not fixed_part or not moving_part:
            continue

        # Structured axis_ranges first (authoritative); prose scrape as
        # fallback for parts whose key_dimensions.axis_ranges is absent
        # (old cache) or doesn't include this axis. The fallback's
        # brittleness is contained to legacy data; new briefs always
        # hit the structured path.
        fixed_r = structured_ranges.get(fixed_part.part_id, {}).get(axis) \
            or _extract_axis_ranges(fixed_part.description, axis)
        moving_r = structured_ranges.get(moving_part.part_id, {}).get(axis) \
            or _extract_axis_ranges(moving_part.description, axis)
        if not fixed_r or not moving_r:
            continue
        if "overall_min" not in fixed_r or "overall_max" not in fixed_r:
            continue
        if "overall_min" not in moving_r or "overall_max" not in moving_r:
            continue

        # Coplanar guard: if the two parts' overall ranges along `axis`
        # overlap by more than 50% of the smaller extent, this is a
        # same-axis-layer joint (e.g. clevis planar chain), NOT a
        # stacking joint. The "seat on +axis face" override below would
        # incorrectly stack the moving part on the +axis side of the
        # fixed part. Skip and keep the LLM's axial_offset_mm (typically
        # 0 for coplanar clevis joints).
        # Robustness: a thick palm (T=25mm) + thin finger (T=8mm) gives
        # overlap_ratio = 8/8 = 1.0 (smaller_extent base), still judged
        # coplanar. Stacked parts (Z=0..8 + Z=8..14) give overlap_ratio
        # = 0 -> override fires.
        f_min = float(fixed_r["overall_min"])
        f_max = float(fixed_r["overall_max"])
        m_min = float(moving_r["overall_min"])
        m_max = float(moving_r["overall_max"])
        overlap = max(0.0, min(f_max, m_max) - max(f_min, m_min))
        smaller_extent = min(f_max - f_min, m_max - m_min)
        overlap_ratio = (
            overlap / smaller_extent if smaller_extent > 0 else 0.0
        )
        if overlap_ratio > 0.5:
            continue

        # Fixed anchor local coord: protrusion midpoint if there's a
        # post/ear/arm, else the overall midpoint (a bar's bore midpoint).
        if "post_min" in fixed_r and "post_max" in fixed_r:
            fixed_anchor_local = (fixed_r["post_min"] + fixed_r["post_max"]) / 2.0
            # The surface the moving seats on is the body's +axis face
            # (the protrusion emerges from the body; the moving sits on
            # the body, not on the protrusion's tip).
            fixed_top_local = fixed_r["overall_max"]
        else:
            fixed_anchor_local = (
                fixed_r["overall_min"] + fixed_r["overall_max"]
            ) / 2.0
            fixed_top_local = fixed_r["overall_max"]

        # Moving anchor local coord: through-bore midpoint = overall midpoint.
        moving_anchor_local = (
            moving_r["overall_min"] + moving_r["overall_max"]
        ) / 2.0

        axial_offset = (
            fixed_top_local + moving_anchor_local - fixed_anchor_local
        )
        overrides[mate.mate_id] = axial_offset

    if not overrides:
        return plan

    new_mates = []
    for mate in plan.mates:
        if mate.mate_id in overrides:
            new_mates.append(mate.model_copy(
                update={"axial_offset_mm": overrides[mate.mate_id]}
            ))
        else:
            new_mates.append(mate)
    return plan.model_copy(update={"mates": new_mates})


def _mate_block(i: int, mate) -> str:
    """Deterministic MateSpec -> AssemblyHelper calls (zero tokens)."""
    fid, mid = mate.fixed_part_id, mate.moving_part_id
    fa, ma = mate.fixed_anchor, mate.moving_anchor
    f_setup, fx, f_dir = _emit_anchor(fa, fid, f"fixed_{mate.mate_id}")
    m_setup, mx, m_dir = _emit_anchor(ma, mid, f"moving_{mate.mate_id}")
    lines = [f"# mate {mate.mate_id} ({mate.mate_type.value}): {fid} <- {mid}"]
    lines += f_setup + m_setup

    if mate.mate_type in (MateType.RIGID, MateType.FACE_TO_FACE):
        # RIGID + axial_offset_mm: shift the fixed frame along the anchor
        # direction (face normal / axis_point axis / SELECTOR axis). Use
        # this to position a moving part at a SPECIFIC offset from the
        # fixed anchor -- e.g. a second ear 90mm to the right of the first
        # ear, when both ears' hole midpoints are the SELECTOR anchors
        # (rigid aligns the two midpoints exactly; axial_offset_mm slides
        # the moving part along the cylinder axis to its actual target X).
        # For FACE_TO_FACE, the face_to_face mate's own offset_mm handles
        # the +Z gap; axial_offset_mm is unused there.
        if mate.mate_type == MateType.RIGID and mate.axial_offset_mm:
            fx_eff = f"_shift_pt({fx}, {f_dir}, {mate.axial_offset_mm!r})"
        else:
            fx_eff = fx
        translation = tuple(float(v) for v in mate.translation_mm)
        if mate.mate_type == MateType.RIGID and translation != (0.0, 0.0, 0.0):
            # translation_mm is expressed in the fixed part's local frame;
            # rotate its basis into world so chained/rotated parents work.
            fx_eff = (
                f"_shift_xyz({fx_eff}, _parts[{fid!r}], {translation!r})"
            )
        moving_rpy = tuple(float(v) for v in mate.moving_rotation_euler_deg)
        moving_frame = f"Location({mx})"
        if moving_rpy != (0.0, 0.0, 0.0):
            # Joint-frame pre-rotation is inverted by connect_to, yielding
            # the requested final moving-part orientation.
            moving_frame += (
                f" * Rotation({-moving_rpy[0]!r}, {-moving_rpy[1]!r}, "
                f"{-moving_rpy[2]!r})"
            )
        lines += [
            f"_f{i} = asm.rigid_frame(_parts[{fid!r}], {('fixed_' + mate.mate_id)!r}, Location({fx_eff}))",
            f"_m{i} = asm.rigid_frame(_parts[{mid!r}], {('moving_' + mate.mate_id)!r}, {moving_frame})",
        ]
        if mate.mate_type == MateType.FACE_TO_FACE:
            lines.append(
                f"asm.face_to_face(_f{i}, _m{i}, offset={mate.offset_mm!r}, "
                f"label={mate.mate_id!r})"
            )
        else:
            lines.append(
                f"asm.connect(_f{i}, _m{i}, relation='rigid', label={mate.mate_id!r})"
            )
    elif mate.mate_type in (MateType.COAXIAL, MateType.REVOLUTE):
        # build123d pairing: RevoluteJoint.connect_to expects a RigidJoint
        # on the moving side -- the fixed side carries the rotation axis.
        # RevoluteJoint's default angular_range is (0, 360): normalize
        # negative static poses into that range (B3). Axis direction comes
        # from the anchor (face normal / axis_point axis / SELECTOR normal).
        # axial_offset_mm (revolute/coaxial only): shift the fixed frame's
        # point along the rotation axis so the moving part seats at the
        # desired axial position. Both anchors resolve to cylinder midpoints
        # by default; without this offset, the moving part floats at the
        # fixed cylinder's midpoint rather than seating on a surface.
        if mate.axial_offset_mm:
            fx_eff = f"_shift_pt({fx}, {f_dir}, {mate.axial_offset_mm!r})"
        else:
            fx_eff = fx
        # Precompensation: build123d's RevoluteJoint.connect_to implicitly
        # reframes the moving part so its local +Z aligns with the fixed
        # axis direction. For axis=+Z this is a no-op (identity rotation),
        # but for axis=+X or +Y the moving part picks up an unwanted
        # ~90° rotation that breaks the joint geometry -- e.g. a finger
        # segment whose long axis is Y ends up along X after the reframe,
        # making the assembled finger lie sideways. Pre-rotate the moving
        # RigidJoint's joint_location by the inverse reframe so build123d's
        # reframe cancels out, leaving the moving part with identity
        # orientation relative to its source geometry. Empirically derived
        # via build123d testing (Rotation(R,P,Y) where RPY produces identity
        # moving orientation after connect_to):
        #   axis=+X → Rotation(0, 90, 180)
        #   axis=+Y → Rotation(-90, 0, -90)
        #   axis=+Z → Rotation(0, 0, 0) (no precomp needed)
        fixed_axis = _anchor_axis_letter(mate.fixed_anchor) or "z"
        _PRECOMP_RPY = {
            "x": (0.0, 90.0, 180.0),
            "y": (-90.0, 0.0, -90.0),
            "z": (0.0, 0.0, 0.0),
        }
        # The moving selector's physical cylinder axis is used to resolve the
        # anchor point, but build123d's moving RigidJoint below receives only
        # Location(point), not that axis.  Therefore real cylinder SELECTOR
        # pairs need the same precompensation as FACE/AXIS_POINT anchors.
        # Skipping it for Y/Y selector pairs leaves connect_to's implicit
        # (-90, 0, -90) reframe on the part (observed in the manifest as a
        # vertical jaw turning sideways).  Apply the axis map uniformly.
        precomp_rpy = _PRECOMP_RPY.get(fixed_axis, (0.0, 0.0, 0.0))
        if precomp_rpy == (0.0, 0.0, 0.0):
            moving_loc_expr = f"Location({mx})"
        else:
            moving_loc_expr = (
                f"Location({mx}) * Rotation({precomp_rpy[0]!r}, "
                f"{precomp_rpy[1]!r}, {precomp_rpy[2]!r})"
            )
        lines += [
            f"_fa{i} = Axis({fx_eff}, {f_dir})",
            f"_f{i} = asm.revolute_frame(_parts[{fid!r}], {('fixed_' + mate.mate_id)!r}, _fa{i})",
            f"_m{i} = asm.rigid_frame(_parts[{mid!r}], {('moving_' + mate.mate_id)!r}, {moving_loc_expr})",
        ]
        if mate.mate_type == MateType.COAXIAL:
            lines.append(
                f"asm.connect(_f{i}, _m{i}, relation='coaxial', label={mate.mate_id!r})"
            )
        else:
            lines.append(
                f"asm.revolute(_f{i}, _m{i}, angle={mate.angle_deg % 360!r}, "
                f"label={mate.mate_id!r})"
            )
    elif mate.mate_type in (MateType.LINEAR, MateType.CYLINDRICAL):
        # LinearJoint / CylindricalJoint.connect_to expect a RigidJoint on
        # the moving side; the fixed side carries the slide axis. The slide
        # DIRECTION comes from mate.slide_axis -- a principal axis in the
        # FIXED part's LOCAL frame, so it is pushed through the part's
        # current location via _world_axis_dir (identity for unmoved parts;
        # chained joints where the fixed part was rotated by a parent mate
        # previously slid along the wrong world axis). The anchor points
        # locate the datum. _validate_mating_plan has already enforced
        # slide_axis == both anchors' principal axis, so consuming slide_axis
        # alone here is consistent with the anchors (the equality check
        # exists to catch architect drift at the stage boundary, not
        # because codegen needs the anchor axis). Default linear_range is
        # (0, inf) -- widen it so negative poses are legal.
        sax = mate.slide_axis or "x"
        sax_dir_expr = f"_world_axis_dir(_parts[{fid!r}], {sax!r})"
        frame_method = (
            "linear_frame" if mate.mate_type == MateType.LINEAR
            else "cylindrical_frame"
        )
        lines += [
            f"_fa{i} = Axis({fx}, {sax_dir_expr})",
            f"_f{i} = asm.{frame_method}(_parts[{fid!r}], {('fixed_' + mate.mate_id)!r}, "
            f"_fa{i}, linear_range=(-100000.0, 100000.0))",
            f"_m{i} = asm.rigid_frame(_parts[{mid!r}], {('moving_' + mate.mate_id)!r}, Location({mx}))",
        ]
        if mate.mate_type == MateType.CYLINDRICAL:
            # CylindricalJoint.relative_to honours `angle`: the static
            # rotation about the slide axis (normalized into [0,360) like
            # revolute).
            lines.append(
                f"asm.connect(_f{i}, _m{i}, relation={mate.mate_type.value!r}, "
                f"position={mate.position_mm!r}, angle={mate.angle_deg % 360!r}, "
                f"label={mate.mate_id!r})",
            )
        else:
            # LinearJoint.relative_to FORCES angle=0.0 for a RigidJoint
            # counterpart (build123d joints.py) -- a nonzero angle_deg would
            # be silently dropped, so _validate_mating_plan rejects it and
            # codegen does not emit it.
            lines.append(
                f"asm.connect(_f{i}, _m{i}, relation={mate.mate_type.value!r}, "
                f"position={mate.position_mm!r}, label={mate.mate_id!r})",
            )
    elif mate.mate_type == MateType.BALL:
        # Ball mate: BallJoint on the fixed (socket) side at the sphere
        # center; RigidJoint on the moving (ball) side at the ball's sphere
        # center. asm.ball() connects them with a 3-tuple `angles` that
        # build123d passes to Rotation(*angles) -- positional slots are
        # (about X, about Y, about Z). The two DOFs are ball_pitch_deg
        # about ball_axis_1 then ball_yaw_deg about ball_axis_2 (defaults
        # y/z: the legacy (0.0, pitch, yaw) tuple); the composed rotation
        # is converted to the equivalent intrinsic-XYZ Euler triple at
        # generation time (see _ball_angles_euler), matching the URDF
        # export's 2-revolute decomposition over the same two axes.
        # Both anchors must be kind=sphere (validated in
        # _validate_mating_plan); fx and mx are the sphere-center 3-tuples
        # from _emit_anchor. angular_range is widened from the default
        # (0,360) to +-360 per slot: relative_to re-derives the
        # orientation and range-checks THAT, so a negative static angle
        # (e.g. pitch=-30) would otherwise raise even though the pose is
        # perfectly valid.
        ex, ey, ez = _ball_angles_euler(
            mate.ball_axis_1, mate.ball_pitch_deg,
            mate.ball_axis_2, mate.ball_yaw_deg,
        )
        lines += [
            f"_f{i} = asm.ball_frame(_parts[{fid!r}], "
            f"{('fixed_' + mate.mate_id)!r}, Location({fx}), "
            f"angular_range=((-360.0, 360.0), (-360.0, 360.0), "
            f"(-360.0, 360.0)))",
            f"_m{i} = asm.rigid_frame(_parts[{mid!r}], "
            f"{('moving_' + mate.mate_id)!r}, Location({mx}))",
            f"asm.ball(_f{i}, _m{i}, "
            f"angles=({ex!r}, {ey!r}, {ez!r}), "
            f"label={mate.mate_id!r})",
        ]
    else:  # pragma: no cover - enum is closed
        lines.append(f"# UNSUPPORTED mate type {mate.mate_type} -> skipped")
    return "\n".join(lines)


def generate_assembly_script(
    brief: AssemblyBrief,
    mates: list,
    repo_root: Path,
    part_step_overrides: "dict[str, str] | None" = None,
) -> str:
    """Render the full ``temp_assembly.py`` source text.

    ``brief`` supplies the parts; ``mates`` (the MatingPlan's MateSpec
    list) supplies placement. The split mirrors MAC's Spec Planner /
    Architect division of labour.
    """
    head = _PRELUDE.format(
        repo_root=str(repo_root),
        assembly_name=brief.assembly_name,
        part_step_overrides=dict(part_step_overrides or {}),
    )

    # Template-only parts (referenced by reuses_part_id but never mated)
    # are geometry sources for reuse instances -- they must NOT be added
    # to the assembly (they would sit at the origin unplaced). The
    # part_builder still generates their STEP; the codegen skips them.
    mated_ids = {
        m.fixed_part_id for m in mates
    } | {m.moving_part_id for m in mates}
    template_only_ids = {
        p.part_id for p in brief.parts
        if any(q.reuses_part_id == p.part_id for q in brief.parts)
        and p.part_id not in mated_ids
    }

    body_lines = []
    for spec in brief.parts:
        if spec.part_id in template_only_ids:
            # Still record the step path (for reuse copy verification)
            # but do NOT asm.add the template into the assembly tree.
            body_lines += [
                f"_step_path = _resolve_part_step({spec.part_id!r})",
                f"_part_steps[{spec.part_id!r}] = str(_step_path)",
            ]
            continue
        body_lines += [
            f"_step_path = _resolve_part_step({spec.part_id!r})",
            f"_parts[{spec.part_id!r}] = asm.add(import_step(_step_path), {spec.part_id!r})",
            f"_part_steps[{spec.part_id!r}] = str(_step_path)",
        ]

    # B1 fix: execute in topological order (fixed parts settle first).
    # Cycle leftovers (invalid plans) are emitted best-effort after; the
    # validation layer flags them upstream before codegen is reached.
    pids = {p.part_id for p in brief.parts}
    ordered = _toposort_mates(mates, pids)
    ordered_ids = {m.mate_id for m in ordered}
    ordered += [m for m in mates if m.mate_id not in ordered_ids]
    for i, mate in enumerate(ordered):
        body_lines.append(_mate_block(i, mate))

    # MateSpec joint limits (D3): carried into assembly_mates.json so the
    # URDF exporter can emit real <limit> bounds instead of borrowing the
    # QA sweep range. Ball mates additionally carry their two DOF axes so
    # the URDF decomposition emits revolute joints about the SAME axes the
    # CAD static pose was composed from.
    mate_limits = {
        m.mate_id: {"limit_lower": m.limit_lower, "limit_upper": m.limit_upper}
        for m in mates
        if getattr(m, "limit_lower", None) is not None
        or getattr(m, "limit_upper", None) is not None
    }
    for m in mates:
        if m.mate_type == MateType.BALL:
            mate_limits.setdefault(m.mate_id, {}).update(
                ball_axis_1=m.ball_axis_1, ball_axis_2=m.ball_axis_2,
            )
    foot = _FOOTER.format(
        step_out="assembly_output.step",
        stl_out="assembly_output.stl",
        manifest_out="assembly_manifest.json",
        mates_out="assembly_mates.json",
        audit_out="assembly_selector_audit.json",
        mate_limits=mate_limits,
    )
    return head + "\n".join(body_lines) + "\n" + foot


def write_assembly_script(
    brief: AssemblyBrief,
    mates: list,
    assembly_dir: Path,
    repo_root: Path,
    iteration: int = 0,
    part_step_overrides: "dict[str, str] | None" = None,
) -> Path:
    """Write ``temp_assembly_{iteration}.py`` into the assembly job dir.

    ``part_step_overrides`` (part_id -> path relative to ``assembly_dir``)
    pins each part's authoritative STEP from the current iteration's
    PartResults so the generated script cannot pick up a stale STEP via
    the mtime glob (see ``_resolve_part_step`` in the prelude).
    """
    src = generate_assembly_script(
        brief, mates, repo_root, part_step_overrides=part_step_overrides
    )
    path = assembly_dir / f"temp_assembly_{iteration}.py"
    path.write_text(src, encoding="utf-8")
    return path


def run_assembly_script(
    script_path: Path,
    assembly_dir: Path,
    *,
    timeout: int,
    python_bin: str = "",
) -> tuple[bool, str]:
    """Execute the generated assembly script (cwd-isolated subprocess)."""
    import os
    import shutil
    import subprocess
    import sys

    # Delete stale outputs from a previous iteration BEFORE running the script.
    # Without this, a script that crashes after import_step but before
    # export_step leaves the prior assembly_output.step on disk; the assembler
    # node still sets assembly_step_path to that path; the QA node's
    # Path(...).is_file() check passes; run_assembly_qa runs detectors on the
    # STALE geometry; if the stale geometry happened to PASS, the router
    # terminates the loop and the user receives the previous iteration's
    # assembly believing it is the new one. Deleting pre-run guarantees a
    # crashed script leaves no STEP, so QA correctly synthesizes FATAL.
    for stale_name in (
        "assembly_output.step",
        "assembly_output.stl",
        "assembly_manifest.json",
        "assembly_mates.json",
        "assembly_selector_audit.json",
    ):
        try:
            (assembly_dir / stale_name).unlink()
        except FileNotFoundError:
            pass
        except OSError:  # pragma: no cover - best-effort cleanup
            pass
    placed_dir = assembly_dir / "placed_stl"
    if placed_dir.is_dir():
        shutil.rmtree(placed_dir, ignore_errors=True)

    python = python_bin or sys.executable
    env = dict(os.environ)
    try:
        proc = subprocess.run(  # noqa: S603
            [python, str(script_path)],
            cwd=str(assembly_dir),
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            timeout=timeout,
        )
        out = proc.stdout or ""
        (assembly_dir / "assembly_log.txt").write_text(out, encoding="utf-8")
        step = assembly_dir / "assembly_output.step"
        ok = proc.returncode == 0 and step.is_file() and step.stat().st_size > 0
        tail = " | ".join(
            ln for ln in out.splitlines() if ln.strip()
        )[-600:]
        return ok, tail
    except subprocess.TimeoutExpired:
        return False, f"assembly script timed out after {timeout}s"
    except Exception as exc:  # noqa: BLE001
        return False, f"assembly script crashed: {exc}"
